### ISSUE TITLE
Pagination code cleanup

### ISSUE THREAD

**Issue by rstorey** [LibraryOfCongress/concordia#220] opened 2018-09-20 00:57 UTC
cleanup task of searching for `request.GET.get("page")` and replacing that view with ListView

**Comment by rstorey** [comment] 2018-09-20 00:58
From @acdha : If you notice I added a standard pagination include which works with anything which provides template variables matching https://ccbv.co.uk/projects/Django/2.0/django.views.generic.list/MultipleObjectMixin/ so we can use that in ListViews and similar.
ccbv.co.uk

**Comment by rstorey** [comment] 2018-09-25 18:35
I think this is already done. I couldn't find `request.GET.get("page")` in the code. @acdha can you confirm?

**Comment by acdha** [comment] 2018-09-25 18:42
I think we can close this as a duplicate of #185

**Closed by acdha** 2018-09-25 18:42 UTC
Labels: coding_standard
