### ISSUE TITLE
Research and diagnose "Unable to save" issue in prototype

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1084] opened 2019-07-30 13:39 UTC
**What behavior did you observe? Please describe the bug**
We've seen/heard feedback about this. 

1 - during the Congressional Scavenger hunt event. Roughly about 10 people at any given time were using the prototype during a two-hour span. Many were getting "Unable to save your work." 

2 - A user also emailed about it. Here is the message below: 

> Carefully, I thought about how to proceed, remembering your advice.
>
> At first, I did not click "edit", I went directly to the interface link.  When I could not interact with the page I returned to page 55.  I made no changes to the page, just clicked "edit", then followed the link to the new interface.  When I clicked "edit" on this page, this message appeared:
> 
> "Unable to save your work This transcription has already been reviewed."
> 
>  Now, not only am I unable to continue on this interface page, when I closed this interface page and returned to page 55, I am UNABLE TO OPEN THIS PAGE NOW, the "edit" button does nothing.
> 
> There is definitely a hitch in my maneuvering between these two.   I shall abandon your new interface for now.  I have no problems with your site otherwise and thoroughly enjoy the work I am doing.  I have been honestly moved by the stories I am reading.  And I enjoy being able to still use all my book publishing skills.

A few users will be typing full pages and then come to this message. This reads to me that they are all trying to work on the same asset and the indicators that help them know that are not clear.

**Comment by acdha** [comment] 2019-07-30 13:58
Do we think this is mostly about providing more prominent explanations for why editing is disabled or is there a confirmed case where it was not disabled but they were unable to save their work? Your first example sounds like the former, which could reflect a problem with the network connection dropping & not receiving the message that someone else has reserved a particular asset.

**Comment by elainekamlley** [comment] 2019-07-30 14:22
Maybe it was a network issue for the first one. Not quite sure. We can do further testing of this in a coffee shop nearby to try and do this not on LOC's network. Having more than 10 people jumping on the same network will be a regular occurrence here and elsewhere. We are being asked more and more to do transcribing cafes by visitor services, so any suggestions as to how to understand the problem at LOC and potential ways to mitigate this are welcomed. It could be that the prototype is not the right interface for these events and we just use the "find a new page" button to avoid reservation issues. 

For the other example. Here is the page link below: 

https://crowd.loc.gov/campaigns/civil-war-soldiers-disabled-but-not-disheartened/left-hand-penmanship-contest/mss13375024/mss13375024-55/

I just did what she did and when I clicked on "Try this page in our new interface", I had to sign. After signing in, I had to go back to the original since it did not take me to that asset after I signed in. Once I got there it says "Asset Reservation in Progress" and the text box is disabled. Went back to the original and it says on the top "Unable to reserve this page: error"

Are the reservations between the original and the prototype in conflict with each other?

**Comment by acdha** [comment] 2019-07-30 14:28
The original and the prototype use the same reservation system, which can also make this potentially confusing since everyone hitting “find a new page” is going to hit the first one in sequence which is available so it's not uncommon that if you need to login and come back someone else might have landed on it in the meantime.

It sounds like we should separately ticket including hash-fragment parameters in the login page's next field value since we added a path where that matters, at least as long as the activity UI doesn't support anonymous users.

**Comment by rstorey** [comment] 2019-09-30 16:48
> **What behavior did you observe? Please describe the bug**
> We've seen/heard feedback about this.
> 
> 1 - during the Congressional Scavenger hunt event. Roughly about 10 people at any given time were using the prototype during a two-hour span. Many were getting "Unable to save your work."
> 

I may be remembering this incorrectly but I believe the main problem with the event was that the same user accounts were logged into more than one machine.

> 2 - A user also emailed about it. Here is the message below:
> 
> > Carefully, I thought about how to proceed, remembering your advice.
> > At first, I did not click "edit", I went directly to the interface link.  When I could not interact with the page I returned to page 55.  

I don't know what "could not interact with the page" means. Maybe not enough time was given to load the page?

I made no changes to the page, just clicked "edit", then followed the link to the new interface.  When I clicked "edit" on this page, this message appeared:
> > "Unable to save your work This transcription has already been reviewed."

This is almost the expected behavior. If the first clicked the Edit button in the old interface, then went to the new interface, the web socket update should cause the new interface to update and take away the buttons. The fallback behavior for when that doesn't work is what the user described. I will look into why the web socket update isn't working, but there could be many reasons why a web socket update fails, not all of which are in our control (e.g. the user has a slow internet connection).


> > Now, not only am I unable to continue on this interface page, when I closed this interface page and returned to page 55, I am UNABLE TO OPEN THIS PAGE NOW, the "edit" button does nothing.

The old interface doesn't live-update when asset status updates unless the user refreshes the page. I don't know what "unable to open this page now" means - does it mean the user tried to refresh the page and it never loaded? If not, then was the user clicking the old Edit button? The beginning part of the user's message was omitted so I'm not sure how page 55 was originally opened or the exact steps that were followed to get to this point. And I can't reproduce this behavior as described.

> > There is definitely a hitch in my maneuvering between these two.   I shall abandon your new interface for now.  I have no problems with your site otherwise and thoroughly enjoy the work I am doing.  I have been honestly moved by the stories I am reading.  And I enjoy being able to still use all my book publishing skills.
> 
> A few users will be typing full pages and then come to this message. This reads to me that they are all trying to work on the same asset and the indicators that help them know that are not clear.

I think this is because different people were logged in to the same user account during the event, which isn't supported. If this happened not during the event, it would be good if we had more detailed reports.

I myself have observed that the live-updating parts of the new interface aren't as live as they're supposed to be. We still need to nail down exact steps to reproduce the issue(s).

**Comment by rstorey** [comment] 2019-09-30 16:52
> Maybe it was a network issue for the first one. Not quite sure. We can do further testing of this in a coffee shop nearby to try and do this not on LOC's network. Having more than 10 people jumping on the same network will be a regular occurrence here and elsewhere. We are being asked more and more to do transcribing cafes by visitor services, so any suggestions as to how to understand the problem at LOC and potential ways to mitigate this are welcomed. It could be that the prototype is not the right interface for these events and we just use the "find a new page" button to avoid reservation issues due to network connection.
> 
> For the other example. Here is the page link below:
> 
> https://crowd.loc.gov/campaigns/civil-war-soldiers-disabled-but-not-disheartened/left-hand-penmanship-contest/mss13375024/mss13375024-55/
> 
> I just did what she did and when I clicked on "Try this page in our new interface", I had to sign. After signing in, I had to go back to the original since it did not take me to that asset after I signed in. Once I got there it says "Asset Reservation in Progress" and the text box is disabled. Went back to the original and it says on the top "Unable to reserve this page: error"
> 
> Are the reservations between the original and the prototype in conflict with each other?

This happened because the page was reserved by anonymous. It should have been omitted from the list of eligible pages to work on after you signed in and loaded the new interface. However the fallback behavior, should that list be incorrect, is for what you described to occur. In this case, since you specified exactly which asset you wanted to work on, I'm not sure whether the list was even a factor because if you specify which asset you want, it loads that asset regardless of whether it's eligible to be in the list. So I'm pretty sure this is as expected.

**Closed** 2019-12-05 16:17 UTC
Labels: Activity UI
