### ISSUE TITLE
Upgrade DB in AWS

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#1328] opened 2021-02-08 18:46 UTC
Support is ending for current version of our database. Need to upgrade. 
 
-----Original Message-----
From: Amazon Web Services, Inc. <no-reply-aws@amazon.com> 
Sent: Wednesday, January 27, 2021 3:37 PM
To: aws-crowd-production <aws-crowd-production@loc.gov>
Cc: danmcgar@amazon.com; olgshepe@amazon.com
Subject: Amazon RDS for PostgreSQL 9.6 End-of-Life date is January 18, 2022 [AWS Account: 619333082511]

Hello, 

*NOTE*: This notice does not apply to Amazon Aurora clusters.

Amazon RDS is starting the end of life (EOL) process for PostgreSQL major version 9.6. We are doing this because the PostgreSQL community is planning to discontinue support for PostgreSQL 9.6 on November 11, 2021 [1].

You are receiving this message because you have one or more PostgreSQL version 9.6 instances in the us-east-1 Region.

Impacted PostgreSQL Databases:
cppbk2akgs950r
cpl1jbd411xj1t
cpi18ys7to10ay
cp1hx946gxs67c4

To avoid availability impact during a time of the year when many customers' databases tend to experience their peak workload, Amazon RDS for PostgreSQL 9.6 will reach EOL on January 18, 2022 00:00:01 AM UTC. While you will be able to run your RDS for PostgreSQL 9.6 databases between community PostgreSQL 9.6 EOL (November 11, 2021) and RDS for PostgreSQL 9.6 EOL (January 18, 2022), the databases will not receive any security patches during this extended availability period. We strongly recommend that you proactively upgrade your RDS for PostgreSQL 9.6 databases to major version 12 or greater before community EOL. PostgreSQL 12 contains major innovations including JSON path queries per SQL/JSON specifications and pluggable table storage interface [2]. PostgreSQL 13 will introduce parallel processing of indexes with the VACUUM command and improved duplicate data handling by B-tree indexes [3]. Both versions contain numerous fixes to various software bugs in earlier versions of the database.

If you do not upgrade your databases before January 18, 2022, RDS will upgrade your PostgreSQL 9.6 databases to 12 during a scheduled maintenance window between January 18, 2022 00:00:01 UTC and February 22, 2022 00:00:01 UTC. On February 22, 2022 00:00:01 AM UTC, any PostgreSQL 9.6 databases that remain will be upgraded to version 12 regardless of whether the instances are in a maintenance window or not.

We recommend that you first upgrade to minor version 9.6.20 or greater and then upgrade directly to PostgreSQL 12 or greater so that you can skip intermediate major versions. You can initiate an upgrade of your database instance either immediately or during your next maintenance window, to a newer version of PostgreSQL using the AWS Management Console or the AWS Command Line Interface. The upgrade process will shut down the database instance, perform the upgrade, and restart the database instance. The database instance may be restarted multiple times during the upgrade process. While major version upgrades typically complete within the standard maintenance window, the duration of the upgrade depends on the number of objects within the database. To avoid any unplanned unavailability outside your maintenance window, we recommend that you first take a snapshot of your database and test the upgrade to get an estimate of the upgrade duration. To learn more about upgrading PostgreSQL major versions in RDS, review the Upgrading Database Versions page [4].

We want to make you aware of the following additional milestones associated with upgrading databases that are reaching EOL.
•	Now through January 18, 2022 00:00:01 AM UTC - You can initiate upgrades of Amazon RDS for PostgreSQL 9.6 instances to PostgreSQL 12 or greater at any time.
•	August 3, 2021 00:00:01 AM UTC - After this date and time, you cannot create new RDS instances with PostgreSQL major version 9.6 from either the AWS Console or the CLI. 
•	January 18, 2022 00:00:01 AM UTC - Amazon RDS will automatically upgrade PostgreSQL 9.6 instances to version 12 within the earliest scheduled maintenance window that follows. After this date and time, restoration of Amazon RDS for PostgreSQL 9.6 database snapshots will result in an automatic upgrade of the restored database to a still supported version at the time.
•	February 22 2022 00:00:01 AM UTC – Amazon RDS will automatically upgrade any remaining PostgreSQL 9.6 instances to version 12 whether or not they are in a maintenance window.

If you have any questions or concerns, the AWS Support Team is available on the community forums and via Premium Support [5].

[1] https://www.postgresql.org/support/versioning/
[2] https://aws.amazon.com/about-aws/whats-new/2019/11/postgresql-12-0-now-available-in-amazon-rds-database-preview-environment/
[3] https://aws.amazon.com/about-aws/whats-new/2020/06/postgresql-13-beta-1-now-available-in-amazon-rds-database-preview-environment/
[4] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Upgrading.html#USER_UpgradeDBInstance.Upgrading.Manual
[5] https://aws.amazon.com/support

Sincerely,
Amazon Web Services

Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210

---
Reference: https://phd.aws.amazon.com/phd/home#/event-log?Event%20ARN=arn:aws:health:us-east-1::event/RDS/AWS_RDS_OPERATIONAL_NOTIFICATION/AWS_RDS_OPERATIONAL_NOTIFICATION_eca20918-2545-4757-8c21-219a93005704&eventID=arn:aws:health:us-east-1::event/RDS/AWS_RDS_OPERATIONAL_NOTIFICATION/AWS_RDS_OPERATIONAL_NOTIFICATION_eca20918-2545-4757-8c21-219a93005704&eventTab=details&layout=vertical

**Comment by jkueloc** [comment] 2021-05-12 14:26
@lalgee both the dev and test databases have been upgraded from 9.6 to 12.  I did the light regression testing in dev yesterday. It would be great if you could do regression testing in test to include admin actions.  I want to be sure nothing new pops up before I upgrade Stage since it's multipurpose and heavily used to vet content before loading to Production.

We also need an acceptable window for upgrading the production database - I have to stop the application service while I update the database.  So I need time for pre-upgrade steps the database upgrade and post upgrade steps.

**Comment by lalgee** [comment] 2021-05-12 14:36
thanks @jkueloc!  i can work on regression testing today.

so the application will be down during the upgrades?  do you have a sense of how long all the steps will take?

**Comment by jkueloc** [comment] 2021-05-12 15:10
@lalgee less than an hour provided I don't screw up anything and nothing unexpected occurs.
I'm updating the detail in the steps I'm capturing as I go so there isn't any guessing on my part when it comes time for production.  Not sure how you want to set expectations with the users.  Better to overestimate time needed (my preference/experience) than under.  Thoughts?

**Comment by lalgee** [comment] 2021-05-12 15:52
Site visits dip between midnight and 8am, so early morning would be best if possible. Our least busy days are Saturday, Sunday, Tuesday, and Wednesday. Upcoming launches are May 26 and June 14 so we also want to steer clear of those. Let us know what will work for you @jkueloc and let's schedule it a week out if possible so we can communicate with users about the outage.

**Comment by lalgee** [comment] 2021-05-12 18:00
@jkueloc I am getting reservation errors for all assets for transcription or review in test ("Unable to reserve this page: error") and am unable to transcribe or review.  Also getting a (500) error for the next-reviewable-asset and next-transcribable-asset links from the homepage.  I haven't completed testing but wanted to go ahead and flag this major issue.

**Comment by jkueloc** [comment] 2021-05-12 18:15
Hi @lalgee - I understand. 
I didn't have that issue at all when testing development yesterday (as documented) or with what little I did in test post upgrade this morning. That said I'm not convinced it's a database upgrade issue.  THere were no errors in the upgrade logs. There were however, several dependabot and other changes merged yesterday afternoon (after my testing) and today.

**Comment by lalgee** [comment] 2021-05-13 15:38
Passed regression testing on frontend and admin module.

**Comment by jkueloc** [comment] 2021-05-13 18:28
The database for stage has been upgraded from Postgres 9.6 to 12.

**Comment by Igor-Ino** [comment] 2021-05-20 14:57
Tested. Functionality looks good, everything works as intended. 
However, there are a couple of minor issues out of this ticket's scope:
1. Clicking on “Let’s go” on a carousel items should lead to the Campaign home page. However, in "Herencia: Legal Spanish Documents" it is going to already started transcription page: https://crowd-test.loc.gov/campaigns/herencia-centuries-of-spanish-legal-documents/next-reviewable-asset/
2. Page “Welcome Guide” has broken link: Revisit the instructions (in all environments, including prod)
3. Incorrect breadcrumbs font encoding, shows Chrome error on this page: https://crowd-test.loc.gov/campaigns/legal-reports/constitutional-issues/2019668243/2019668243-19/  (same error in prod, too)
4. Blue type in the footer (all pages) still is very low contrast.

**Comment by lalgee** [comment] 2021-05-20 17:43
Thanks @Igor-Ino!

1. The Let's go button url is configurable in the carousel module.  We usually point it to the campaign page, but sometimes use the "next transcribable asset" or "next reviewable asset functionality. So it is working as designed.
2. I've updated the broken "Revisit the instructions" link in all environments -- thanks for spotting!
3. Can you say more about the font error?  Is it that the Cyrillic (?) characters are showing up in a different font?

It sounds like 3 and 4 should both be ticketed as design issues.

**Comment by Igor-Ino** [comment] 2021-05-20 19:58
Issue 3: this is Cyrillic transliteration, I am attaching image how it works in FF compared to Chrome. I was thrown on this page when I tested the button "Surprise me." (Actually, this Russian translation was executed with multiple typos, I have fixed 2 pages, then understood it would take too long to fix all 30 pages). 
I am not sure why, but encoding is different in Chrome.
![Chrome](https://user-images.githubusercontent.com/80710853/119041140-40dd5200-b984-11eb-939c-f6ba7f40b7a4.jpg)

**Comment by lalgee** [comment] 2021-05-21 14:13
Thanks for the review contributions!  :)

My Chrome also has an issue with the text but it does display it, just in a different font:
![image](https://user-images.githubusercontent.com/20258744/119151026-fbb92e80-ba1c-11eb-9105-28e5b893f939.png)
![image](https://user-images.githubusercontent.com/20258744/119151169-1f7c7480-ba1d-11eb-95a0-ef02be564d4e.png)

**Comment by Igor-Ino** [comment] 2021-05-21 14:58
I think this can be fixed by changing font in CSS or avoid using artificial diphthongs in breadcrumbs or titles in metadata. I think that use non-standard letters in title would lead to more confusion in search, than doing good for scientific purposes, because it is not fully correct or justified. For example, the same title is missing diphthongs in the word Soedinennykh, which should be then transliterated as Soyedinyonnykh or as in attached file: 
![Soedinennykh](https://user-images.githubusercontent.com/80710853/119157732-7b49fc00-ba23-11eb-9135-e26fbe576759.jpg)

**Comment by lalgee** [comment] 2021-05-21 15:34
@Igor-Ino Makes sense!  Are you ok with ticketing the font and footer issues for @klee72 ?

**Comment by Igor-Ino** [comment] 2021-05-21 16:17
@lalgee Sure, will do.

**Closed** 2021-05-21 16:18 UTC
Labels: infrastructure

**Comment by klee72** [comment] 2021-05-21 16:57
@Igor-Ino @lalgee Color update is not completed yet, but if you create a new ticket then I can use the ticket to commit the changes. Also I don't know which sprint that you're testing but the test environment doesn't look like it's updated with latest UI updates.

**Comment by Igor-Ino** [comment] 2021-05-21 17:30
@lalgee @klee72  Created ticket #1447 and #1448
