### ISSUE TITLE
Simple pages render using Markdown syntax but admin preview supports CommonMark

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#722] opened 2018-12-14 22:17 UTC
**What behavior did you observe? Please describe the bug**
As a community manager, I made a list in static text using markdown.  It appears as a list in the preview window but does not include line breaks when saved/in place on the website

**How can we reproduce the bug?**
Edit a static page to include a markdown list.  Save and refresh the page.

**What is the expected behavior?**
I expect the list to display as bulleted items with line breaks between

**Got screenshots? This helps us identify the issue**
How the list looks in the editor
![image](https://user-images.githubusercontent.com/20258744/50032784-cf836300-ffc3-11e8-8221-a8295dae22c2.png)

How the list looks in preview
![image](https://user-images.githubusercontent.com/20258744/50032790-db6f2500-ffc3-11e8-9621-5ce6831bd96b.png)

How the list looks on on crowd-test
![image](https://user-images.githubusercontent.com/20258744/50032687-6e5b8f80-ffc3-11e8-8f31-34476f8c7537.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Found in testing #616

**Comment by acdha** [comment] 2018-12-15 01:19
This looks like an incompatibility between the two markdown libraries being used. Did you try with a line before the start of the list? That’s usually required but different parsers may be more forgiving. Prettier should add one for you automatically, too.

**Comment by elainekamlley** [comment] 2018-12-17 14:40
@acdha The issue persists after adding a space and/or after running prettier

**Comment by acdha** [comment] 2018-12-17 16:00
We didn’t change the markdown renderer and the page display didn’t change for our existing pages when I was testing it so, based on the screenshot above showing a slightly different syntax I was assuming this was just a discrepancy with the preview system around an under-specified part of the spec. Now that you’re saying it doesn’t affect rendering, however, it’s unclear what’s being reported.

**Comment by acdha** [comment] 2018-12-17 16:22
I just did a test and confirmed that this is what I thought: a discrepancy between the Python markdown parser we've been using on the site and the JavaScript parser which drives the live preview. This appears to be the subject of [some discussion in the standardization process](https://talk.commonmark.org/t/blank-lines-before-lists-revisited/1990) because it's [not supported by most implementations](http://johnmacfarlane.net/babelmark2/?text=This+is+a+test%0A-+foo%0A-+bar%0A%0Athis+is+a+test+with+line+breaks+as+required+by+most+Markdown+implementations%3A%0A%0A-+foo%0A-+bar).

The easiest way to avoid this is to always put a blank line before a list:

```markdown
This is a test
- foo
- bar

this is a test with line breaks as required by many Markdown parsers:

- foo
- bar
```

The second list always renders as a list across many different Markdown parsers but the first varies widely. I confirmed that clicking the “Run Prettier” button will do this for you.

I'm not sure what the best resolution for this issue is — it's technically working as designed but I don't like the live preview handling syntax variations inconsistently so perhaps the best answer is to either see whether we can get a JavaScript parser which acts more like pymarkdown or consider switching to CommonMark-py and the JS counterpart.

**Comment by acdha** [comment] 2018-12-18 20:36
We should decide where to prioritize this — the two options are either switching our Python code to use [CommonMark](https://pypi.org/project/CommonMark/) or to replace Remarkable.js with something which implements the original Markdown spec.

**Comment by rstorey** [comment] 2019-06-14 20:08
Considering that the preview in the admin mode is only there for convenience, doesn't reflect the CSS that will be present on the public page, and pages should be checked on the regular site before publishing changes to production, I don't think either option is worth the time. I think we should close this.

**Comment by rstorey** [comment] 2019-07-08 20:12
Works as designed

**Closed by rstorey** 2019-07-08 20:12 UTC
Labels: bug, community manager
