### ISSUE TITLE
Fix email confirmation link is a example.com link and not a crowd link.

### ISSUE THREAD

**Issue by elainekamlley** [LibraryOfCongress/concordia#380] opened 2018-10-12 18:05 UTC
Acceptance criteria 

- [ ] In the email that is sent to users, the link that they need to click to confirm their email should be a crowd link and not example.com

**Comment by acdha** [comment] 2018-10-12 20:53
This is a configuration issue: in the admin, the sites section allows you to change the canonical display name and URL which many things use, including that email.

We should probably have the deployment process seed the intended public URL automatically.

**Comment by rstorey** [comment] 2018-10-15 22:32
Dupe of #392

**Closed by rstorey** 2018-10-15 22:32 UTC
Labels: bug
