### ISSUE TITLE
Better transition when a user needs to switch content or activity

### ISSUE THREAD

**Issue by lalgee** [LibraryOfCongress/concordia#668] opened 2018-11-27 20:40 UTC
**Is your feature request related to a problem? Please describe.**

For example, currently, when a project only contains completed OR in review assets, there is a banner over even the in-review items that says "There are no remaining pages to be transcribed in this project". The item says "Submitted for Review" small above the transcription window. It's unclear therefore what the user can/should do on this page. (see screenshot)
![image](https://user-images.githubusercontent.com/20258744/49109662-4b0db200-f259-11e8-810f-8e507f088da4.png)

**user acceptance criteria**
- After the action is completed, a user will have a options to go anther item
- 

**Additional context**
Possibly part of #607

**Comment by VVH** [comment] 2018-11-27 21:18
And related to #647

**Comment by acdha** [comment] 2018-11-27 21:18
The “no remaining pages to be transcribed” message is added when you click “find a new page” and it normally would only be displayed once on the next page, which is either a project or campaign detail page:

https://github.com/LibraryOfCongress/concordia/blob/742bc401eb7d7a35fbf65ec62e4bda495f5fc870/concordia/views.py#L1134

The screenshot above suggests a browser incompatibility which is preventing that logic from working so normally we'd need to figure out what broke it (I couldn't reproduce that in either Chrome or Firefox) but that was always a stopgap for the postponed task to change the behaviour of the “find a new page” view when there are no available pages. 

Currently it stores the message and redirects you to either the project or campaign detail page but we've been wanting to change that for awhile to incorporate some sort of landing message which would suggest ways to find other tasks to do. Implementing that would avoid needing to figure out how to reproduce the environment which produced the screenshot above (I couldn't reproduce it in Chrome or Firefox) and it seems like it'd be good to have a standard display for ways you can contribute anyway since as you noted it seems like it could help with on-boarding and we also have some related challenges with e.g. explaining what the statuses mean (we don't have room to put a huge amount of text on the default page but some sort of popup or link seems appropriate).

**Comment by acdha** [comment] 2019-01-15 16:46
For the portion of this ticket which is changing where the find-next-page view sends you, one simple option would be making the campaign / project pages more direct - maybe something like collapsing the progress bar statistics as in #640 to create room for an action banner which is focused on what the user can specifically do and reusing some of the homepage style:

![image](https://user-images.githubusercontent.com/46565/51195253-b881aa80-18ba-11e9-8134-2d7fbc05d5be.png)

One other thought is that we [currently redirect to the project/campaign pages](https://github.com/LibraryOfCongress/concordia/blob/7881be06b458bd3c308caf84975aaf02296331f5/concordia/views.py#L1186-L1191) which can be problematic if certain activity categories have no remaining work in that campaign/project. One alternative could be either revising the campaign listing itself or creating a tabular view which would show which activities are currently available and doing something like sorting it by the last thing the user did so they could try to stick with the same activity / campaign but could easily switch if something else caught their eye.

**Comment by rstorey** [comment] 2019-07-08 20:05
Closing as dupe of #785

**Closed by rstorey** 2019-07-08 20:05 UTC
Labels: review process
